version: "2"
services:
  redis:
    image: redis
    restart: always
    container_name: handee-redis
    expose:
      - 6379
    ports:
      - "6379:6379"

  mongo:
    image: mongo
    restart: always
    container_name: handee-mongo
    expose:
      - 27017
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
